version: '3.8'

services:
  jupyter-gpu-torch-tf:
    build:
      context: .
    image: jupyter_lab_cv
    container_name: jupyter_lab_cv
    ports:
      - "8789:8789"
    volumes:
      - /home/alex/Dev/CV/playground:/playground
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1